[package]
name = "advent_of_code"
version = "0.8.0"
authors = ["Matthew McGarvey"]
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
